NAMESPACE="apic"

# kubectl timeout
# format: "10s", "1m"
REQUEST_TIMEOUT="10s"

RUNNING_RESOURCES=(
  "gw/gwv6"
  "a7s/analytics"
)

READY_RESOURCES=(
  "cert/gwv6-endpoint"
)

EVENTS_RESOURCES=(
  "gw/gwv6"
  "a7s/analytics"
)